# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:09
from __future__ import unicode_literals

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookiecutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_in_seller',
            name='seller',
            field=models.ForeignKey(
                default="1", on_delete=django.db.models.deletion.CASCADE, to='cookiecutter.Seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url_in_seller',
            name='url',
            field=models.CharField(default='url', max_length=1000, validators=[
                                   django.core.validators.URLValidator()]),
        ),
    ]
