# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookiecutter', '0003_cutter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookiecutter.Category')),
            ],
        ),
        migrations.AddField(
            model_name='cutter',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cutter',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookiecutter.Category'),
        ),
    ]
